name: 'Jira Release Notes'
description: 'This action generate release notes markdown from Jira project by version'
inputs:
  domain:
    description: 'Domain name(https://your-domain.atlassian.net)'
    required: true
  project:
    description: 'Project name'
    required: true
  version:
    description: 'Version name'
    required: true
  auth-token:
    description: 'Jira API token key'
    required: true

outputs:
  release_notes:
    description: 'Release notes (Markdown format)'
runs:
  using: 'node16'
  main: 'dist/index.js'